### ISSUE TITLE
考虑更换一下图标？

### ISSUE THREAD

**Issue by pi1ot** [jianzhichun/vscode-translate#1]
![unnamed-2](https://cloud.githubusercontent.com/assets/1677644/19924235/045b7a80-a126-11e6-959d-80ba09f30248.png)
![unnamed](https://cloud.githubusercontent.com/assets/1677644/19924234/045b0aa0-a126-11e6-93d4-73169a978dd0.png)
![translation](https://cloud.githubusercontent.com/assets/1677644/19924236/045c6ddc-a126-11e6-8085-23679cb5080d.jpg)

**Comment by jianzhichun** [comment]
非常抱歉 现在才回答这个issues， 因为前段时间有点忙， 对于图标 我可能会再考虑一下，因为个人比较喜欢简单抽象的风格，嘿嘿
