### ISSUE TITLE
add option to change translation API?

### ISSUE THREAD

**Issue by archonwang** [jianzhichun/vscode-translate#2]
add option to change translation API?

**Comment by jianzhichun** [comment]
You mean that we can change the way of translation? 
Sorry for Late reply. 
I'll begin this now.

**Comment by lemoatom** [comment]
谷歌的翻译质量会好很多。
另外能一键翻译替换就好了。

**Comment by jianzhichun** [comment]
替换是将翻译结果替换到原文中吗

**Comment by jianzhichun** [comment]
由于google api的收费，translate 页面的结果也是用js动态生成等原因，目前还不自持google翻译， 现在的版本增加了不同语言的翻译自持， 可以在用户设置里配置[link](https://github.com/jianzhichun/vscode-translate#it-will-read-httpproxy-at-user-settings-to-get-data-by-proxy), 并且 按ctrl+shift+r可以替换选中内容[link](https://github.com/jianzhichun/vscode-translate#and-you-can-press-ctrlshiftr-to-replace-selected-text-to-result-after-translation)

**Comment by archonwang** [comment]
@jianzhichun , yes.
Thanks.

**Comment by lemoatom** [comment]
@jianzhichun 太棒了！

**Comment by lemoatom** [comment]
看到个翻译网页内容的Chrome扩展，支持多个接口，希望能有所帮助。
https://github.com/Selection-Translator/crx-selection-translate
https://github.com/Selection-Translator/translation.js

当然，目前已经很好用了，大大提高了文本翻译的效率。再次表示很赞！

**Comment by jianzhichun** [comment]
好的， 谢谢

**Comment by jianzhichun** [comment]
加了google 翻译api的支持 可以通过设置translation.api 来改变 目前只支持baidu&google

**Comment by lemoatom** [comment]
你这效率高的不行
