### ISSUE TITLE
能否拆分驼峰命名法，并进行翻译呢

### ISSUE THREAD

**Issue by zwq000** [jianzhichun/vscode-translate#7]
vscode 经常用来看代码，很常见的驼峰命名方法，一个名称很长，也是用多个单词拼接而成的。
比如说 ColorAnimationUsingKeyFrames，
这个名称翻译不出来，还是原样的内容。
如果加上空格 就是 Color Animation Using Key Frames，这样 意思是  

> 使用关键帧的彩色动画

考虑到很多前端构造的命名方法通过 - / _ 等，还是很有用的。

**Comment by jianzhichun** [comment]
好主意，等空下来就实现他。

**Comment by jianzhichun** [comment]
@zwq000 不好意思 一直以来都没放重心到这里。现在有驼峰翻译到效果了。

![image](https://user-images.githubusercontent.com/17561654/40958406-befc3cf8-68cb-11e8-8345-780c1e95e11d.png)
