### ISSUE TITLE
翻译不生效了？

### ISSUE THREAD

**Issue by evanxue76** [jianzhichun/vscode-translate#9]
"ctrl+t"后提示"translate on"，但是划词之后左下角并没有翻译后的文字显示。

vscode版本

![tim 20180504160716](https://user-images.githubusercontent.com/20034875/39618216-57781fd6-4fb5-11e8-9fa9-e2ba7cb91911.jpg)

已经安装的全部插件

![tim 20180504160737](https://user-images.githubusercontent.com/20034875/39618239-6621d9dc-4fb5-11e8-870a-5aa38b4e29be.jpg)

是只有我这样吗？

**Comment by jianzhichun** [comment]
sorry, 版本高的不兼容了。工作太忙， 下周过后才有空，会升级它。

**Comment by V0idk** [comment]
@jianzhichun 加油啊

**Comment by xbynet** [comment]
@V0idk 厉害了我的哥，赶紧给作者提个pr

**Comment by jianzhichun** [comment]
@V0idk @PolarPig 新的版本0.1.2上线了， 试试

**Comment by jianzhichun** [comment]
@V0idk @PolarPig 之前是因为老的使用百度的api方式不行了，目前上线的0.1.3 版本用的google-translate-api-cn， 后面再研究怎么用百度的。 另外添加了驼峰或者下划线的翻译能力， 以及DidYouMean的消息推送。 希望有空帮忙测下。

**Comment by 946629031** [comment]
加油啊  哥们，等你的翻译了

**Comment by jianzhichun** [comment]
@946629031 额，这个已经close了。现在的版本不能用吗？
